[package]
name = "fwupd-dbus"
version = "0.1.1"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
license = "MIT"
description = "fwupd dbus client bindings"
repository = "https://github.com/pop-os/fwupd-dbus"

[dependencies]
dbus = "0.8.2"
shrinkwraprs = "0.3.0"
err-derive = "0.2.3"
bitflags = "1.2.1"
reqwest = { version = "0.10.4", features = ["blocking"] } 
crypto-hash = "0.3.4"
hex-view = "0.1.3"
cascade = "0.1.4"
xdg = "2.2.0"
url = "2.1.1"
progress-streams = "1.1.0"
log = "0.4.8"
